### ISSUE TITLE
Don't panic if the execution context does not supply all of the fields present in the filter.

### ISSUE THREAD

**Issue by kornstar11** [cloudflare/wirefilter#64]
Hello,
I ran across this panic while using Wirefilter in my project:
https://github.com/cloudflare/wirefilter/blob/master/engine/src/execution_context.rs#L41

If the field is not set on the ExecutionContext should we just consider it a non matching result? Wanted to discuss this since there are probably cases I am not thinking about (maybe if something is not equal ? ).

Also, if you would like I could take a stab at implementing a fix.

Thank you.

**Comment by inikulin** [comment]
Hi, thank you for the proposal.

We are not considering implementing this, because it effectively introduces `null` values into the language. And with that we have 3 options:
1. Implicit null to type coalescing - plagues dynamic languages and it's a design decision to keep filters strictly typed to reduce the range of possible programming errors.
2. Switch to [ternary logic](https://en.wikipedia.org/wiki/Three-valued_logic) - will turn the language into esoteric.
3. Explicit null to type coalescing - is the best option available, though if you want dynamically substitute values for null that will never be implemented as it will introduce Turing completeness. If you always replace `null` with the same values then it can be done during the construction of the execution context - just replace absent values with defaults that suit your needs.

**Comment by kornstar11** [comment]
Thank you for your insight. I will take your suggestion as outlined in option #3 and just set some defaults upfront.
